version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /backend
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    groups:
      mui-major-updates:
        patterns:
          - "@mui/*"
        update-types:
          - major
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
